### PR TITLE
update faq.json

### PR DESCRIPTION
**Pull request by milindgoel15**

### CODE REVIEW

**Comment by KevinX8** [comment]
json is broken

**Comment by milindgoel15** [comment]
Where?

**Comment by KevinX8** [comment]
The build status says where, it's still failing rn

**Comment by milindgoel15** [comment]
the bot is high af now

**Comment by KevinX8** [comment]
@milindgoel15 I can't merge if the json is broken btw

**Comment by milindgoel15** [comment]
> @milindgoel15 I can't merge if the json is broken btw
> 

It ain't broken tho. Check with jsonlint and it will say valid. Don't know why this bot has issues now

**Comment by KevinX8** [comment]
Valid is different from following the schema, the bot checks if you follow the schema and you don't

**Pull request closed without merging**
